### ISSUE TITLE
Big Refactoring of JmzReader 

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Utilities/jmzReader#10]
@jgriss @mbdebian @Tobias-Ternent :

Hi guys jmzReader is used in most of our components in PRIDE and the current structure of the project make really difficult to deploy, integrate with the libraries, etc. Most of our components: ms-data-core-api, archive-pipeline, etc use all the readers and is becoming more challenge to keep track of versions of the libraries, the reader, etc. Most of these modules only contain one class on have only one dependency. We have been discussing the refactoring of jmzReader to version 2.0 merging all the modules in one module starting with the version 2.0.0-SNAPSHOT. This will enable: 

1- Easy deploy of the library.
2- Better integration with other tools in PRIDE Archive. 
3- Easy to maintain, develop, extend. 

Best Regards and give me a +1 if you agree. 

Yasset

**Comment by jgriss** [comment]
:+1:

I originally did this since we weren't sure at all in which direction this project would go. So yes, this change is very sensible!

**Comment by mbdebian** [comment]
Once you're done, don't forget to review the CI system to check that your refactoring is "green", and double check on all the possible artifacts that may be broken because of the changes.
![screen shot 2017-07-06 at 13 33 48](https://user-images.githubusercontent.com/8855107/27911159-f75d9c28-624f-11e7-9371-43c7931b6971.png)

**Comment by mbdebian** [comment]
Also, I thought you were going to do all the refactoring within a separated branch, not on the master one.

**Comment by ypriverol** [comment]
the reason of that problem is that some of the libraries inside are mapping to something else. I will check all the libraries that depend on jmReader and change the version. I will take care of the complete process. thanks @mbdebian for the feedback ... we need to update the plans

**Comment by ypriverol** [comment]
No I'm doing it on a separate branch. The commit is failing is another i did in the morning with some bug fixing.

**Comment by mbdebian** [comment]
I suspect the plans running on Bamboo won't need any update, as they rely on Maven for testing the software, as long as the main POM file for jmzReader doesn't change much, i.e. it stays integrated with our CI setup.

**Comment by ypriverol** [comment]
related with this @jgriss are you using the GUI? we can remove this export and leave this responsibility in inspector that can open all the files.

**Comment by jgriss** [comment]
I like the GUI since it's quite fast. But I only use it very rarely. Nevertheless, adapting the GUI to the new infrastructure shouldn't be that much work? But I leave the decision with you, how you want to proceed.

**Comment by ypriverol** [comment]
Done!!!!
