### ISSUE TITLE
How this fork relates to https://code.google.com/p/jmzreader/ ?

### ISSUE THREAD

**Issue by wolski** [PRIDE-Utilities/jmzReader#3]
Hi,

I am planning to use jmzreader and I am just wondering how this fork relates to : https://code.google.com/p/jmzreader/ ? 

Are the developers at google code not active anymore?

Are you planning also to move (or did you moved it and I am just missing it) the documentation (wiki)  from google to github?
https://code.google.com/p/jmzreader/w/list

best regards

**Comment by ypriverol** [comment]
Hi wolski:
 This is the current "official" fork of the previous google code project maintained by the PRIDE team 
 and PSI community. 
 The development in google conde is not any more active, we are committing and maintaining the 
 library using this this project. 
 The documentation must be here, if not I will create an issue and update it. 

 We also just release the evolution of jmzReader library for identification and other file formats here if 
 your are interested: (https://github.com/PRIDE-Utilities/ms-data-core-api)

Regards 
Yasset

**Comment by ypriverol** [comment]
@wolski please close the issue if you are happy with this !!!

**Comment by wolski** [comment]
Thanks for the information.

**Comment by wolski** [comment]
Actually a suggestion. If this is indeed the official fork, would you be please so kind and provide a linke to this repository from the google code page
https://code.google.com/p/jmzreader/

?!

**Comment by ypriverol** [comment]
Thanks for this suggestion, I will do it, and also to other libraries from @HUPO-PSI, thanks for this suggestion.
