### ISSUE TITLE
Can I skip the xxindex part, directly read all mzXML into the memory?

### ISSUE THREAD

**Issue by fcyu** [PRIDE-Utilities/jmzReader#4]
Hi,

I found that the indexing part is quite slow because of the disk I/O. Since we have large RAM now, can we skip the indexing part, directly read mzXML into the memory, and do the parsing?

Thanks,

fcyu

**Comment by ypriverol** [comment]
We have been thinking in this option for mzML fora while. The first approach was done with ms-data-core-api (https://github.com/PRIDE-Utilities/ms-data-core-api) where we implement independently the mzML from the peak lists. You can try and let us know.

**Comment by fcyu** [comment]
What about mzXML? I found that ms-data-core-api calls jmzXML to parse mzXML. Is that means that reading mzXML is still slow?

Thanks,

**Comment by ypriverol** [comment]
We can take a look to the mzXML, to implement the same mechanism that mzML. If you want to contribute with the library you are more than welcome to fork do the changes and I can review it and merge them.
